package api.entity;

public class BannerItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_item.id
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_item.img_id
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    private Integer imgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_item.key_word
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    private String keyWord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_item.type
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_item.delete_time
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    private Integer deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_item.banner_id
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    private Integer bannerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_item.update_time
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    private Integer updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_item.id
     *
     * @return the value of banner_item.id
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_item.id
     *
     * @param id the value for banner_item.id
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_item.img_id
     *
     * @return the value of banner_item.img_id
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public Integer getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_item.img_id
     *
     * @param imgId the value for banner_item.img_id
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_item.key_word
     *
     * @return the value of banner_item.key_word
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public String getKeyWord() {
        return keyWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_item.key_word
     *
     * @param keyWord the value for banner_item.key_word
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public void setKeyWord(String keyWord) {
        this.keyWord = keyWord == null ? null : keyWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_item.type
     *
     * @return the value of banner_item.type
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_item.type
     *
     * @param type the value for banner_item.type
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_item.delete_time
     *
     * @return the value of banner_item.delete_time
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public Integer getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_item.delete_time
     *
     * @param deleteTime the value for banner_item.delete_time
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public void setDeleteTime(Integer deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_item.banner_id
     *
     * @return the value of banner_item.banner_id
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public Integer getBannerId() {
        return bannerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_item.banner_id
     *
     * @param bannerId the value for banner_item.banner_id
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public void setBannerId(Integer bannerId) {
        this.bannerId = bannerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_item.update_time
     *
     * @return the value of banner_item.update_time
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_item.update_time
     *
     * @param updateTime the value for banner_item.update_time
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }
}