package api.entity;

public class Banner {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.id
     *
     * @mbg.generated Thu May 24 15:51:51 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.name
     *
     * @mbg.generated Thu May 24 15:51:51 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.description
     *
     * @mbg.generated Thu May 24 15:51:51 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.delete_time
     *
     * @mbg.generated Thu May 24 15:51:51 CST 2018
     */
    private Integer deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.update_time
     *
     * @mbg.generated Thu May 24 15:51:51 CST 2018
     */
    private Integer updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.id
     *
     * @return the value of banner.id
     *
     * @mbg.generated Thu May 24 15:51:51 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.id
     *
     * @param id the value for banner.id
     *
     * @mbg.generated Thu May 24 15:51:51 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.name
     *
     * @return the value of banner.name
     *
     * @mbg.generated Thu May 24 15:51:51 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.name
     *
     * @param name the value for banner.name
     *
     * @mbg.generated Thu May 24 15:51:51 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.description
     *
     * @return the value of banner.description
     *
     * @mbg.generated Thu May 24 15:51:51 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.description
     *
     * @param description the value for banner.description
     *
     * @mbg.generated Thu May 24 15:51:51 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.delete_time
     *
     * @return the value of banner.delete_time
     *
     * @mbg.generated Thu May 24 15:51:51 CST 2018
     */
    public Integer getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.delete_time
     *
     * @param deleteTime the value for banner.delete_time
     *
     * @mbg.generated Thu May 24 15:51:51 CST 2018
     */
    public void setDeleteTime(Integer deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.update_time
     *
     * @return the value of banner.update_time
     *
     * @mbg.generated Thu May 24 15:51:51 CST 2018
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.update_time
     *
     * @param updateTime the value for banner.update_time
     *
     * @mbg.generated Thu May 24 15:51:51 CST 2018
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }
}