package api.entity;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.id
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.name
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.topic_img_id
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    private Integer topicImgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.delete_time
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    private Integer deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.description
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.update_time
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    private Integer updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.id
     *
     * @return the value of category.id
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.id
     *
     * @param id the value for category.id
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.name
     *
     * @return the value of category.name
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.name
     *
     * @param name the value for category.name
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.topic_img_id
     *
     * @return the value of category.topic_img_id
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public Integer getTopicImgId() {
        return topicImgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.topic_img_id
     *
     * @param topicImgId the value for category.topic_img_id
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public void setTopicImgId(Integer topicImgId) {
        this.topicImgId = topicImgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.delete_time
     *
     * @return the value of category.delete_time
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public Integer getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.delete_time
     *
     * @param deleteTime the value for category.delete_time
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public void setDeleteTime(Integer deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.description
     *
     * @return the value of category.description
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.description
     *
     * @param description the value for category.description
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.update_time
     *
     * @return the value of category.update_time
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.update_time
     *
     * @param updateTime the value for category.update_time
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }
}