package api.entity;

public class OrderProduct extends OrderProductKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product.count
     *
     * @mbg.generated Thu May 24 15:51:51 CST 2018
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product.delete_time
     *
     * @mbg.generated Thu May 24 15:51:51 CST 2018
     */
    private Integer deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product.update_time
     *
     * @mbg.generated Thu May 24 15:51:51 CST 2018
     */
    private Integer updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product.count
     *
     * @return the value of order_product.count
     *
     * @mbg.generated Thu May 24 15:51:51 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product.count
     *
     * @param count the value for order_product.count
     *
     * @mbg.generated Thu May 24 15:51:51 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product.delete_time
     *
     * @return the value of order_product.delete_time
     *
     * @mbg.generated Thu May 24 15:51:51 CST 2018
     */
    public Integer getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product.delete_time
     *
     * @param deleteTime the value for order_product.delete_time
     *
     * @mbg.generated Thu May 24 15:51:51 CST 2018
     */
    public void setDeleteTime(Integer deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product.update_time
     *
     * @return the value of order_product.update_time
     *
     * @mbg.generated Thu May 24 15:51:51 CST 2018
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product.update_time
     *
     * @param updateTime the value for order_product.update_time
     *
     * @mbg.generated Thu May 24 15:51:51 CST 2018
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }
}