package api.entity;

import java.math.BigDecimal;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_no
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_id
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.delete_time
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    private Integer deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.create_time
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    private Integer createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.total_price
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    private BigDecimal totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.status
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.snap_img
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    private String snapImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.snap_name
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    private String snapName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.total_count
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    private Integer totalCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.update_time
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    private Integer updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.snap_address
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    private String snapAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.prepay_id
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    private String prepayId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.snap_items
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    private String snapItems;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_no
     *
     * @return the value of order.order_no
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_no
     *
     * @param orderNo the value for order.order_no
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_id
     *
     * @return the value of order.user_id
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_id
     *
     * @param userId the value for order.user_id
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.delete_time
     *
     * @return the value of order.delete_time
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public Integer getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.delete_time
     *
     * @param deleteTime the value for order.delete_time
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public void setDeleteTime(Integer deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.create_time
     *
     * @return the value of order.create_time
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.create_time
     *
     * @param createTime the value for order.create_time
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.total_price
     *
     * @return the value of order.total_price
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.total_price
     *
     * @param totalPrice the value for order.total_price
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.status
     *
     * @return the value of order.status
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.status
     *
     * @param status the value for order.status
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.snap_img
     *
     * @return the value of order.snap_img
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public String getSnapImg() {
        return snapImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.snap_img
     *
     * @param snapImg the value for order.snap_img
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public void setSnapImg(String snapImg) {
        this.snapImg = snapImg == null ? null : snapImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.snap_name
     *
     * @return the value of order.snap_name
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public String getSnapName() {
        return snapName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.snap_name
     *
     * @param snapName the value for order.snap_name
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public void setSnapName(String snapName) {
        this.snapName = snapName == null ? null : snapName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.total_count
     *
     * @return the value of order.total_count
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public Integer getTotalCount() {
        return totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.total_count
     *
     * @param totalCount the value for order.total_count
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public void setTotalCount(Integer totalCount) {
        this.totalCount = totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.update_time
     *
     * @return the value of order.update_time
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.update_time
     *
     * @param updateTime the value for order.update_time
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.snap_address
     *
     * @return the value of order.snap_address
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public String getSnapAddress() {
        return snapAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.snap_address
     *
     * @param snapAddress the value for order.snap_address
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public void setSnapAddress(String snapAddress) {
        this.snapAddress = snapAddress == null ? null : snapAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.prepay_id
     *
     * @return the value of order.prepay_id
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public String getPrepayId() {
        return prepayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.prepay_id
     *
     * @param prepayId the value for order.prepay_id
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public void setPrepayId(String prepayId) {
        this.prepayId = prepayId == null ? null : prepayId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.snap_items
     *
     * @return the value of order.snap_items
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public String getSnapItems() {
        return snapItems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.snap_items
     *
     * @param snapItems the value for order.snap_items
     *
     * @mbg.generated Thu May 24 19:33:32 CST 2018
     */
    public void setSnapItems(String snapItems) {
        this.snapItems = snapItems == null ? null : snapItems.trim();
    }
}